version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev-backend
    container_name: guitar-backend-dev
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py
  frontend:
    image: node:22-alpine
    container_name: guitar-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
  admin-panel:
    image: node:22-alpine
    container_name: guitar-admin-dev
    working_dir: /app
    ports:
      - "5174:5174"
    volumes:
      - ./AdminPanel:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
